version: '3.8'

services:
  todo-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: discord-todo-bot
    restart: unless-stopped
    environment:
      - WEEKLY_PLANNING_CHANNEL_ID=1368180016785002536
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - TIMEZONE=Europe/Berlin
    env_file:
      - ../.env  # Use the production bots .env file
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - todo-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "simple_health.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.docker.compose.project=discord-bots"
      - "com.docker.compose.service=todo-bot"

networks:
  todo-network:
    driver: bridge
    name: discord-todo-network

volumes:
  logs:
    driver: local
  data:
    driver: local
